---
- name: Remove Nginx on CentOS
  hosts: CentOS
  gather_facts: no # fact는 ansible의 변수, OS 등 여러 정보들을 저장하는데, 비활성화 시 성능향상
  become: yes # sudo 로 실행

  tasks:
    - name: remove epel-release
      yum: name=epel-release state=absent

    - name: remove nginx web server
      yum: name=nginx state=absent

- name: Remove ngfinx on Ubuntu
  hosts: Ubuntu
  gather_facts: no
  become: yes

  tasks:
    - name: remove nginx web server
      apt: pkg=nginx state=absent autoremove=yes
