---
- hosts: all
  become: true
  vars:
    tomcat_version: 9.0.39

    tomcat_permissions_production: True

    tomcat_users:
      - username: "tomcat"
        password: "wogml23"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "exampleuser"
        password: "wogml23"
        roles: "tomcat"
  roles:
    - role: zaxos.tomcat-ansible-role
