# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ansible-server" do |cfg|
    cfg.vm.box = "generic/centos7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Server(github_SysNet4Admin)"
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end
    cfg.vm.host_name="ansible-server"
    cfg.vm.network "public_network", ip:"192.168.0.10", bridge: "en0: Wi-Fi (Wireless)"
    cfg.vm.provision "shell", inline: "sudo yum install epel-release -y"
    cfg.vm.provision "shell", inline: "yum install ansible -y"
    cfg.vm.provision "file", source: "tomcat", destination: "tomcat"
    cfg.vm.provision "shell", inline: "ansible-playbook tomcat/site.yml"
  end
end
