---
- name: Setup CentOS timezone
  hosts: CentOS :Ubuntu
  gather_facts: no
  become: yes

  tasks:
    - name: set timezone to Asia/Seoul
      timezone: name=Asia/Seoul

- name: Setup windows timezone
  hosts: Windows
  gather_facts: no

  tasks:
    - name: set timezone to 'Korea Standard Time'
      win_timezone: timezone='Korea Standard Time'
# check linux time
# ans all -m shell -a "timedatectl | grep 'Time zone'" -k

# check windows time
# ans Windows -m win_shell -a "powershell Get-TimeZone" -k
